version: '3.7'
services:
  app:
    build: .
    ports:
      - 8501:8501
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - homepage.group=Applications
      - homepage.name=Colony Counter
      - homepage.icon=/icons/colony-counter.png
      - homepage.href=https://colony-counter.server.sigmondkukla.dev
      - homepage.description=Tool for counting colonies on agar plates
      - homepage.ping=https://colony-counter.server.sigmondkukla.dev
  restart: unless-stopped

networks:
  default:
    external: true
    name: nginxproxymanager